baseURL: "https://alyuzberil.github.io/" 
title: Beril Alyuz Yilmaz
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Resume
          url: BAY_CV_2025.pdf
          weight: 3

params:
    description: "This website hosts Beril Alyuz Yilmaz's research papers, publications, course materials, curriculum vitae, and contact information."
    author: Beril Alyuz Yilmaz
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Beril Alyuz Yilmaz
          subtitle: "I am a PhD student in Bioengineering at UCLA, focusing on MRI, Deep Learning, Computer Vision, Image Reconstruction & Synthesis, and Super-resolution. Previously, I completed my MSc in Electrical and Electronics Engineering at Bilkent University."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: Talks
              url: talks/
            - name: Resume
              url: BAY_CV_2025.pdf

    socialIcons:
        - name: Email
          url: mailto:alyuzberil@gmail.com
        - name: GitHub
          url: https://github.com/alyuzberil
        - name: LinkedIn
          url: https://www.linkedin.com/in/alyuzberil/
        - name: Phone
          url: tel:+13108738065

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Beril Alyuz Yilmaz"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2